import { Router } from "express";
import { prisma } from "../db/client.js";
import { z } from "zod";
import { computeNextOccurrence } from "./recurrence.js";

export const transferRoutes = Router();

// ── Schemas ───────────────────────────────────────────────────────────────────

const transferRuleSchema = z.object({
  description: z.string().min(1),
  amount: z.number().positive(),
  frequency: z.enum(["DAILY", "WEEKLY", "MONTHLY", "YEARLY"]),
  interval: z.number().int().positive().default(1),
  startDate: z.string(),
  endDate: z.string().optional().nullable(),
  fromAccountId: z.string(),
  toAccountId: z.string(),
});

const transferSchema = z.object({
  description: z.string().min(1),
  amount: z.number().positive(),
  date: z.string(),
  notes: z.string().optional().nullable(),
  fromAccountId: z.string(),
  toAccountId: z.string(),
  isConfirmed: z.boolean().optional().default(false),
  // If provided, creates a recurring rule and links this transfer to it
  recurrence: z
    .object({
      frequency: z.enum(["DAILY", "WEEKLY", "MONTHLY", "YEARLY"]),
      interval: z.number().int().positive().default(1),
      endDate: z.string().optional().nullable(),
    })
    .optional()
    .nullable(),
});

// ── TransferRule routes ───────────────────────────────────────────────────────

// List all active transfer rules
transferRoutes.get("/rules", async (_req, res) => {
  const rules = await prisma.transferRule.findMany({
    where: { isActive: true },
    include: {
      fromAccount: { select: { id: true, name: true, color: true, type: true } },
      toAccount: { select: { id: true, name: true, color: true, type: true } },
    },
    orderBy: { createdAt: "asc" },
  });
  res.json(rules);
});

// Update a transfer rule
transferRoutes.put("/rules/:id", async (req, res) => {
  const parsed = transferRuleSchema.partial().safeParse(req.body);
  if (!parsed.success) return res.status(400).json({ error: parsed.error.flatten() });

  const { startDate, endDate, ...rest } = parsed.data;
  const rule = await prisma.transferRule.update({
    where: { id: req.params.id },
    data: {
      ...rest,
      ...(startDate !== undefined && { startDate: new Date(startDate) }),
      ...(endDate !== undefined && { endDate: endDate ? new Date(endDate) : null }),
    },
    include: {
      fromAccount: { select: { id: true, name: true, color: true, type: true } },
      toAccount: { select: { id: true, name: true, color: true, type: true } },
    },
  });
  res.json(rule);
});

// Archive (soft-delete) a transfer rule and its pending transfers
transferRoutes.post("/rules/:id/archive", async (req, res) => {
  const { id } = req.params;

  await prisma.$transaction([
    prisma.transferRule.update({
      where: { id },
      data: { isActive: false },
    }),
    // Remove future unconfirmed transfers generated by this rule
    prisma.transfer.deleteMany({
      where: {
        transferRuleId: id,
        isConfirmed: false,
        date: { gte: new Date() },
      },
    }),
  ]);

  res.status(204).send();
});

// ── Transfer routes ───────────────────────────────────────────────────────────

// List transfers (optionally filter by accountId and/or date range)
transferRoutes.get("/", async (req, res) => {
  const { accountId, from, to, confirmed } = req.query;

  const where: Record<string, unknown> = {};

  if (accountId) {
    where.OR = [
      { fromAccountId: accountId as string },
      { toAccountId: accountId as string },
    ];
  }

  if (from || to) {
    const dateFilter: Record<string, Date> = {};
    if (from) dateFilter.gte = new Date(from as string);
    if (to) dateFilter.lte = new Date(to as string);
    where.date = dateFilter;
  }

  if (confirmed !== undefined) {
    where.isConfirmed = confirmed === "true";
  }

  const transfers = await prisma.transfer.findMany({
    where,
    include: {
      fromAccount: { select: { id: true, name: true, color: true, type: true } },
      toAccount: { select: { id: true, name: true, color: true, type: true } },
      transferRule: { select: { id: true, description: true, frequency: true, interval: true } },
    },
    orderBy: { date: "asc" },
  });

  res.json(transfers);
});

// Create a transfer (optionally with a recurring rule)
transferRoutes.post("/", async (req, res) => {
  const parsed = transferSchema.safeParse(req.body);
  if (!parsed.success) return res.status(400).json({ error: parsed.error.flatten() });

  const { description, amount, date, notes, fromAccountId, toAccountId, isConfirmed, recurrence } =
    parsed.data;

  const transferDate = new Date(date);

  let transfer;

  if (recurrence) {
    // Create the rule first, then the first Transfer instance linked to it
    const rule = await prisma.transferRule.create({
      data: {
        description,
        amount,
        frequency: recurrence.frequency,
        interval: recurrence.interval,
        startDate: transferDate,
        endDate: recurrence.endDate ? new Date(recurrence.endDate) : null,
        nextOccurrence: computeNextOccurrence(transferDate, recurrence.frequency, recurrence.interval),
        fromAccountId,
        toAccountId,
      },
    });

    transfer = await prisma.transfer.create({
      data: {
        description,
        amount,
        date: transferDate,
        notes: notes ?? null,
        fromAccountId,
        toAccountId,
        transferRuleId: rule.id,
        isConfirmed: isConfirmed ?? false,
      },
      include: {
        fromAccount: { select: { id: true, name: true, color: true, type: true } },
        toAccount: { select: { id: true, name: true, color: true, type: true } },
        transferRule: { select: { id: true, description: true, frequency: true, interval: true } },
      },
    });
  } else {
    transfer = await prisma.transfer.create({
      data: {
        description,
        amount,
        date: transferDate,
        notes: notes ?? null,
        fromAccountId,
        toAccountId,
        isConfirmed: isConfirmed ?? false,
      },
      include: {
        fromAccount: { select: { id: true, name: true, color: true, type: true } },
        toAccount: { select: { id: true, name: true, color: true, type: true } },
        transferRule: true,
      },
    });
  }

  res.status(201).json(transfer);
});

// Update a transfer
transferRoutes.put("/:id", async (req, res) => {
  const parsed = transferSchema.omit({ recurrence: true }).partial().safeParse(req.body);
  if (!parsed.success) return res.status(400).json({ error: parsed.error.flatten() });

  const { date, ...rest } = parsed.data;
  const transfer = await prisma.transfer.update({
    where: { id: req.params.id },
    data: {
      ...rest,
      ...(date !== undefined && { date: new Date(date) }),
    },
    include: {
      fromAccount: { select: { id: true, name: true, color: true, type: true } },
      toAccount: { select: { id: true, name: true, color: true, type: true } },
      transferRule: { select: { id: true, description: true, frequency: true, interval: true } },
    },
  });
  res.json(transfer);
});

// Confirm a transfer (mark as cleared)
transferRoutes.post("/:id/confirm", async (req, res) => {
  const transfer = await prisma.transfer.findUnique({ where: { id: req.params.id } });
  if (!transfer) return res.status(404).json({ error: "Transfer not found" });

  const updated = await prisma.transfer.update({
    where: { id: req.params.id },
    data: { isConfirmed: true },
    include: {
      fromAccount: { select: { id: true, name: true, color: true, type: true } },
      toAccount: { select: { id: true, name: true, color: true, type: true } },
    },
  });
  res.json(updated);
});

// Delete a transfer (and optionally its rule + future siblings)
transferRoutes.delete("/:id", async (req, res) => {
  const deleteFuture = req.query.deleteFuture === "true";

  const transfer = await prisma.transfer.findUnique({ where: { id: req.params.id } });
  if (!transfer) return res.status(404).json({ error: "Transfer not found" });

  if (deleteFuture && transfer.transferRuleId) {
    await prisma.$transaction([
      prisma.transferRule.update({
        where: { id: transfer.transferRuleId },
        data: { isActive: false },
      }),
      prisma.transfer.deleteMany({
        where: {
          transferRuleId: transfer.transferRuleId,
          isConfirmed: false,
          date: { gte: transfer.date },
        },
      }),
    ]);
  } else {
    await prisma.transfer.delete({ where: { id: req.params.id } });
  }

  res.status(204).send();
});

// Generate upcoming transfer instances from active rules
// (mirrors the generateUpcomingExpenses pattern in the expenses route)
export async function generateUpcomingTransfers(): Promise<void> {
  const WINDOW_DAYS = 60;
  const windowEnd = new Date();
  windowEnd.setDate(windowEnd.getDate() + WINDOW_DAYS);

  const rules = await prisma.transferRule.findMany({
    where: {
      isActive: true,
      nextOccurrence: { lte: windowEnd },
    },
  });

  for (const rule of rules) {
    let next = new Date(rule.nextOccurrence);

    while (next <= windowEnd) {
      if (!rule.endDate || next <= rule.endDate) {
        // Upsert: use (transferRuleId, date) match to avoid duplicates
        const existing = await prisma.transfer.findFirst({
          where: { transferRuleId: rule.id, date: next },
        });

        if (!existing) {
          await prisma.transfer.create({
            data: {
              description: rule.description,
              amount: rule.amount,
              date: next,
              fromAccountId: rule.fromAccountId,
              toAccountId: rule.toAccountId,
              transferRuleId: rule.id,
              isConfirmed: false,
            },
          });
        }
      }

      next = computeNextOccurrence(next, rule.frequency, rule.interval);
    }

    // Advance nextOccurrence on the rule
    await prisma.transferRule.update({
      where: { id: rule.id },
      data: { nextOccurrence: next },
    });
  }
}
